### ISSUE TITLE
Check hardware availability

### ISSUE THREAD

**Issue by ineiti** [c4dt/service-spindle#13]
- [x] run multiple nodes on demo.c4dt.org
  - [x] ask support-icit@epfl.ch for possibility of having a server with 64GB of RAM
    - [x] mail sent, waiting for answer
  - [x] check how much a node with 64GB of RAM costs on Switch
    - [x] check if snapshot and 'stopped' node is free or cheaper than running node

**Comment by tharvik** [comment]
Switch cost for 64G RAM per month is 480 Frs, which is not cheap. The cost is counted for running & suspended machines so we can start it only when needed.
We might also be able to get the 25% reduction for educational project.

**Comment by ineiti** [comment]
> The cost is counted for running & suspended machines so we can start it only when needed.

Do you mean "The cost is NOT counted for suspended machines"? Else it doesn't change anything if we start them only when needed...

**Comment by tharvik** [comment]
> > The cost is counted for running & suspended machines so we can start it only when needed.
> 
> Do you mean "The cost is NOT counted for suspended machines"? Else it doesn't change anything if we start them only when needed...

"suspended" means "saved to RAM", so it is counted in this case. "shelved" is a snapshot associated to a shuted down machine.

From IC-IT
> The XaaS (VM provider) don't have servers with 64GB.
