### ISSUE TITLE
Verify why the prediction is wrong

### ISSUE THREAD

**Issue by ineiti** [c4dt/service-spindle#14]
When running the demo.c4dt.org/spindle, the calculated value is wrong. Is it
- wrong representation?
- not enough training rounds? use ICCluster to check if more rounds help

**Comment by tharvik** [comment]
So, when loading the CSV with the server, the CLI didn't allow for which side of the dataset was the nominal/results column and defaulted to the left, which was wrong for the PIMA dataset.
See ldsec/spindle#29 for the fix.
