### ISSUE TITLE
remove concurrent training limitation

### ISSUE THREAD

**Issue by tharvik** [c4dt/service-spindle#26]
In #21, we've remove the possibility of running concurrent training. Now that the server is big enough, we can remove this limitation. @ineiti is that okay with you?

**Comment by ineiti** [comment]
Can you start manually three trainings in parallel and write here how long it takes? Please do 3 runs. Manually ;)

**Comment by tharvik** [comment]
It took: 19s, 20s, 20s, with the default settings.

**Comment by ineiti** [comment]
So it's the same speed in parallel as it is in sequential? If yes, then it's good for me to remove the restriction. I'd keep it as a boolean in the config, we might run into it again once we make the dataset bigger ;)

**Comment by tharvik** [comment]
It's kept as a patchset in `c4dt_patchset` for now then.
