### ISSUE TITLE
bump deps

### ISSUE THREAD

**Issue by tharvik** [c4dt/service-spindle#31]
- [ ] bump onet/cothority to have better error messages
- [ ] bump others

**Comment by tharvik** [comment]
SwissRe/LDS sent me a mail about encountering an "unknown error".

**Comment by tharvik** [comment]
Bumping to latest `@dedis/cothority` forces me to install `@types/url-parse`
> ERROR in node_modules/@dedis/cothority/network/websocket.d.ts:3:17 - error TS7016: Could not find a declaration file for module 'url-parse'. '/home/tharvik/c4dt/service-spindle/webapp/node_modules/url-parse/index.js' implicitly has an 'any' type.
  Try `npm install @types/url-parse` if it exists or add a new declaration (.d.ts) file containing `declare module 'url-parse';`

Which doesn't *compile* on my system (some `node-gyp rebuild` failing)..

https://github.com/dedis/cothority/commit/63a28eda7 says that
> As the dedis/cothority is not only used in the browser, but also in node and nativescript, URL cannot be used reliably.

Is it still the case? Is there some NS or Node running somewhere? `webpack` should take care of the "platform specific transformation" supposedly, but we all know the story.

At least, `@types/url-parse` should be moved from dev deps to "main" deps, as the type is exposed in `network.WebSocketConnection`. I don't think it will resolve my problem but who knows.

@ineiti WDYT?

**Comment by ineiti** [comment]
Oh my - no real idea here. After all these years I'm still (or again) confused about node/ts/js/webpack/...

So for the node part I had to add `url-parse`. But I have a PR that removes mobile, so perhaps there is no need for node anymore. Except if the DEDIS still uses it for the pop-app?

With regard to `node-gyp`, for my side-project using rust, I had to install it as a dependency of the project itself. Can you try that?

**Comment by tharvik** [comment]
> So for the node part I had to add `url-parse`. But I have a PR that removes mobile, so perhaps there is no need for node anymore. Except if the DEDIS still uses it for the pop-app?

I'd remove it from cothority in a PR and ask Noemien to review it.

> With regard to `node-gyp`, for my side-project using rust, I had to install it as a dependency of the project itself. Can you try that?

It is actually installed by my package manager but a deps of `url-parse` really wants to use its own local version..

**Comment by ineiti** [comment]
But is it in the `package.json`?

**Comment by tharvik** [comment]
>>> With regard to `node-gyp`, for my side-project using rust, I had to install it as a dependency of the project itself. Can you try that?
>>>
>> It is actually installed by my package manager but a deps of `url-parse` really wants to use its own local version..
>>
> But is it in the `package.json`?

Indirectly, and I've tested it in a tmp `package.json`, to no avail.
