### ISSUE TITLE
Idea to show the data is hidden

### ISSUE THREAD

**Issue by ineiti** [c4dt/service-spindle#33]
Instead of showing the data of the three nodes, start with all three nodes covered by a gray sheet with a big `Node x` on top. Once the user clicks on the node, a pop-up appears with something like:

`This data is hidden in the node and cannot be seen by the querier. Only updates to the model in encrypted form will ever leave this node. For demonstration purposes, however, you can have a look at the data.`

**Comment by ineiti** [comment]
Wonderful!

**Comment by tharvik** [comment]
For the record, the `revealer` component is implement in c4dt/angular-components, it should be reusable.
